version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schema_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/

  localstack:
    image: localstack/localstack
    container_name: localstack_container
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1

volumes:
  postgres_data:
